workflows:
  default-workflow:
    name: Max2D Android
    max_build_duration: 60
    environment:
      vars:
        FCI_CLONE_UNSHALLOW: 'true'
      flutter: 1.22.6
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - cd . && flutter packages pub get
      - cd . && flutter build apk --release --ignore-deprecation
      - cd . && flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
