name: Dart CI

on: 
 workflow_dispatch

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       distribution: 'temurin' # See 'Supported distributions' for available options
       java-version: '17'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 2.10.3
    # Get flutte
    - run: flutter pub get --ignore-deprecation
    # Build :D 
    - run: flutter build --ignore-deprecation
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
