name: Dart CI

on: 
 workflow_dispatch:
 push:

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       distribution: 'temurin' # See 'Supported distributions' for available options
       java-version: '16'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.6
    # Get flutte
    - run: flutter packages pub get 
    # Build :D 
    - run: flutter build apk --release
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
