name: test
on:
  workflow_dispatch:
  push:
    branches:
    - stage

env:
  FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
